site_name: neuralmagic/speculators Documentation
site_description: Comprehensive documentation for neuralmagic/speculators
site_url: https://neuralmagic.github.io/speculators/
repo_url: https://github.com/neuralmagic/speculators
repo_name: neuralmagic/speculators
edit_uri: edit/main/docs/
docs_dir: docs
nav:
- Home: index.md
- Overview: overview.md
- Installation: installation.md
- Configuration: configuration.md
- Development: development.md
theme:
  name: material
  palette:
  - scheme: default
    primary: blue
    accent: blue
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  - navigation.instant
  - navigation.top
  - search.highlight
  - search.share
  - content.code.copy
  - content.action.edit
  - content.action.view
  icon:
    repo: fontawesome/brands/github
plugins:
- search
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.tabbed
- pymdownx.tasklist
- toc
- tables
- attr_list
- md_in_html
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/neuralmagic/speculators
  generator: false
